#include <stddef.h>
/*
 * Standalone reproducer — build with ASan.
 * Generated by SAILOR (concrete_verify.py).
 */
/* AUTO-GENERATED REPLAY DRIVER for concrete validation
 * Replaces symbolic inputs with concrete ktest values.
 * Compile with ASan: gcc -fsanitize=address -g -O0 replay_driver.c ... -o replay
 */
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "harness_types.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef tmsize_t
typedef long tmsize_t;
#endif

extern tmsize_t TIFFWriteEncodedTile(struct TIFF* tif, uint32_t tile, void* data, tmsize_t cc);

int LLVMFuzzerTestOneInput(const uint8_t *fuzz_data, size_t fuzz_size) {
    if (fuzz_size < 20) return 0;
    // Allocate TIFF and its directory concretely
    struct TIFF *tif = (struct TIFF*)calloc(1, sizeof(struct TIFF));
    struct TIFFDirectory *td = (struct TIFFDirectory*)calloc(1, sizeof(struct TIFFDirectory));

    // Initialize directory fields (concrete or symbolic). Avoid 0 to bypass div-by-zero paths.
    td->td_stripsperimage = 1; // non-zero to keep normal flow; UAF will still trigger on read
    td->td_fillorder = 0;

    tif->tif_dir = td;

    // Prepare call arguments
    uint32_t tile;
    { memcpy(&tile, fuzz_data + 0, 4); }

    tmsize_t cc = 16;  // concrete size for buffer growth simulation
    void *data = malloc((size_t)cc);
    if (!data) return 0;
    { memcpy(data, fuzz_data + 4, 16); }

    // Call entry directly (pass-through to vulnerable slice)
    (void)TIFFWriteEncodedTile(tif, tile, data, cc);

    return 0;
}
