/*
 * KLEE driver — symbolic execution entry for tif_write.c:503 (CWE-416).
 * Generated by the SAILOR LLM harness.
 * Compile to LLVM IR and run with klee --libc=uclibc --posix-runtime.
 */
#include <klee/klee.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include "harness_types.h"

#ifndef tmsize_t
typedef long tmsize_t;
#endif

extern tmsize_t TIFFWriteEncodedTile(struct TIFF *tif, uint32_t tile,
                                     void *data, tmsize_t cc);

int main(void) {
    /* 1) Concretely allocate the TIFF context and its directory. */
    struct TIFF          *tif = (struct TIFF *)calloc(1, sizeof(struct TIFF));
    struct TIFFDirectory *td  = (struct TIFFDirectory *)calloc(1, sizeof(struct TIFFDirectory));
    tif->tif_dir = td;

    /* 2) Symbolic directory fields that flow into line 503. */
    klee_make_symbolic(&td->td_stripsperimage, sizeof(td->td_stripsperimage),
                       "td_stripsperimage");
    klee_make_symbolic(&td->td_fillorder,      sizeof(td->td_fillorder),
                       "td_fillorder");

    /* Avoid div-by-zero paths so the symbolic engine reaches the UAF site. */
    klee_assume(td->td_stripsperimage != 0);

    /* 3) Symbolic call arguments. */
    uint32_t tile;
    klee_make_symbolic(&tile, sizeof(tile), "tile");

    tmsize_t  cc   = 16;                 /* bounded buffer size */
    void     *data = malloc((size_t)cc);
    klee_make_symbolic(data, (size_t)cc, "data_buf");

    /* 4) Invoke the sliced entry; KLEE explores paths that may realloc
     *    tif->tif_dir and then dereference the stale `td` on line 503. */
    (void)TIFFWriteEncodedTile(tif, tile, data, cc);
    return 0;
}
